import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ScrollProvider } from "@/components/ScrollContext";
import "./globals.css";
import Navbar from "@/components/Navbar";
import LogoLoader from "@/components/Logoloader";
import { Merriweather } from "next/font/google";
import Footer from "@/components/Footer";

const merriweather = Merriweather({
  weight: ["400", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin", "latin-ext"],
  display: "swap",
  variable: "--font-merriweather",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.variable} ${geistSans.variable} ${geistMono.variable} antialiased max-w-screen overflow-x-hidden`}
      >
        <ScrollProvider>
          <LogoLoader>
            <main>
              <Navbar />
            </main>
            {children}
          <Footer />
          </LogoLoader>
        </ScrollProvider>
      </body>
    </html>
  );
}
